### ISSUE TITLE
 Brownout detector was triggered when powering of CR2450

### ISSUE THREAD

**Issue by sillevl** [rbaron/w-parasite#1]
When powering the circuit from a CR2450 battery, I only get brownout's and the code never starts...

```
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8

Brownout detector was triggered
```

I would have expected this behaviour as the ESP requires a large current at startup and wifi communication. How did you solve this problem? I see pictures from you using an CR2450 battery.

**Comment by rbaron** [comment]
Hey there. I use a LIR2450 Li-Ion battery here, but I had a similar problem. On occasion, the brownout detector was tripping me up.

I think a proper solution (short of using a beefier LiPo/Li-Ion battery) would be to stick a really big capacitor across the power lines, but that comes at comes at a cost (charging up the cap, self discharge). I unfortunately had to disable the brownout detector (done [here](https://github.com/rbaron/w-parasite/blob/main/code/src/main.cpp#L35), with a heartfelt comment). I really dislike having to do this, and I am both happy and disappointed that it works.

The bottomline for me is that it is super tricky to get the ESP32 to run well on tiny batteries. I moved the design to use BLE and a nRF52 chip in [rbaron/b-parasite](https://github.com/rbaron/b-parasite).

**Comment by sillevl** [comment]
@rbaron thanks for the feedback. I have tested it with LIR2450 cells as wel, but after 2 hours it just dies. Might be an old cell. I ordered some new ones to be sure. 
I knew ESP's and coin cells are a real challenge. I just hoped you figured it out :) 
I might try to build a sensor using LoRaWAN and an STM32L4 microcontroller. I have build some low power devices using that configuration in the past.
